site_name: FastAPI Application
site_description: API Documentation
site_author: Your Name
repo_url: https://github.com/yourusername/ReallyLastTry

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_signature_return_annotation: true
            show_bases: true
            show_submodules: true
            heading_level: 2
            docstring_options:
              trim_doctest_flags: true
              ignore_init_summary: true

nav:
  - Home: index.md
  - API Reference:
      - Configuration: reference/config.md
      - Services: reference/services.md
      - Models: reference/models.md
  - Development:
      - Setup: development/setup.md
      - Testing: development/testing.md
      - Contributing: development/contributing.md
