name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          curl -sSL https://cli.railway.app/install.sh | sh

      - name: Railway Login
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --ci --token $RAILWAY_TOKEN

      - name: Deploy
        run: railway up --yes
